name: Deploy Bicep
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Container tag
        required: true
        default: v1
jobs:
  deploy-bicep:
    runs-on: ubuntu-latest
    env:
      CONTAINER_HOST: "ghcr.io/opsdojo"
      CONTAINER_VERSION: "${{ github.event.inputs.tag == '' && 'v1' || github.event.inputs.tag }}"
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Create script for module publishing
      run: |
        cat << 'EOF' > publish-modules.sh
        #!/bin/bash
        shopt -s globstar
        for file in ./bicep-modules/**/*.bicep; do
          [ -f "$file" ] || continue
          module="${file/%\.bicep/:${{ env.CONTAINER_TAG }}}"
          cr_target = "br:${{ env.ACR_HOST }}/${module:2}"
          echo "$file --> $cr_target"
          az bicep publish -f "$file" -t $cr_target --force
        done
        EOF
        chmod +x publish-modules.sh

    - name: Upsert modules
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
          mcr.microsoft.com/azure-cli:latest ./publish-modules.sh
