name: Deploy Bicep
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Container tag
        required: true
        default: v1
jobs:
  deploy-bicep:
    env:
      CONTAINER_TAG: ":${{ github.event.inputs.tag == '' && 'v1' || github.event.inputs.tag }}"
      ACR_HOST: "ghcr.io/opsdojo"
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Create script for module publishing
      run: |
        cat << 'EOF' > publish-modules.sh
        #!/bin/bash
        shopt -s globstar
        for file in ./bicep-modules/**/*.bicep; do
          [ -f "$file" ] || continue
          module="${file/%\.bicep/${CONTAINER_TAG}}"
          echo "$file --> br:${ACR_HOST}/${module:2}"
          az bicep publish -f "$file" -t "br:${ACR_HOST}/${module:2}" --force
        done
        EOF
        chmod +x publish-modules.sh

    - name: Upsert modules
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
          mcr.microsoft.com/azure-cli:latest ./publish-modules.sh
